server:
  port: 8082

spring:
  application:
    name: notification
  profiles:
    active: default

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
