server:
  port: 8082

spring:
  application:
    name: notification
#  profiles:
#    active: default
  data:
    mongodb:
      # User "noti" is created from mongo-init.js file being uploaded to mongodb container.
      #      uri: mongodb://noti:noti@localhost:27017/notification
      database: notification
      host: mongo
      port: 27017
      username: noti
      password: noti
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
