server:
  port: 8081

spring:
  application:
    name: fraud
  profiles:
    active: default
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5433/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  # All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
