server:
  port: 8761

spring:
  application:
    name: eureka-server
#  profiles:
#    active: default

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
